from model import Database, AccountConfig, ChatRoomConfig, ChatMessageConfig


AccountConfig.create_table_on_database(database_engine=Database.engine)
ChatRoomConfig.create_table_on_database(database_engine=Database.engine)
ChatMessageConfig.create_table_on_database(database_engine=Database.engine)
