from model import Database, AccountConfig, ChatRoomConfig, ChatMessageConfig


AccountConfig.create_table_on_database(database_engine=Database.ENGINE)
ChatRoomConfig.create_table_on_database(database_engine=Database.ENGINE)
ChatMessageConfig.create_table_on_database(database_engine=Database.ENGINE)
