from model import DefinedDB, AccountConfig, ChatRoomConfig, ChatMessageConfig


AccountConfig.create_table_on_database(database_engine=DefinedDB.engine)
ChatRoomConfig.create_table_on_database(database_engine=DefinedDB.engine)
ChatMessageConfig.create_table_on_database(database_engine=DefinedDB.engine)
